copy format_overrides only after correcting data
This fixes

	panicked at 'we only ever put Human* colors into the dictionary', src/lib.rs:521:22

because we know where the Corrected bits of the format information
will be immediately upon new(), but that doesn't affect the payload bits
that are corrected each update() call.

Fixes: 2d82f9942d3a ("check all combinations of format bits for BCH code")